### PR TITLE
Add support for joystick hats.

### PR DESCRIPTION
**Pull request by MolarAmbiguity**
Needed this for project, thought I'd contribute it back.

### CODE REVIEW

**Comment by tesselode** [comment]
Nice! I never use joysticks, so I don't know what the hats are generally used for. Does it make more sense to think of each of the 8 directions as different buttons, or would it make more sense to have a "right" button that detects up-right, right, and down-right, a "down" button that detects down-left, down, and down-right, etc.? This would make it closer to the behavior of axes, but I don't know if that makes sense with the connotation of joystick hats in games.

**Comment by MolarAmbiguity** [comment]
I'm writing an utility to bind unsupported gamepads to sdl gamepads, using [love.joystick.setGamepadMapping](https://love2d.org/wiki/love.joystick.setGamepadMapping). On my gamepad the dpad is detected as a hat. 

I think it makes the most sense to detect hats as 8 separate buttons, since this makes it easier to accurately distinguish [complex inputs](http://streetfighter.wikia.com/wiki/Inputs#.27Complex.27_Inputs) like 'quarter circle forward' and 's'.

**Comment by tesselode** [comment]
Do you think it would also make sense to detect dpads as 8 different buttons?

**Comment by MolarAmbiguity** [comment]
Like dpads in general? Even on a recognised gamepad?

**Comment by tesselode** [comment]
Yeah! I mean, not necessarily as the only behavior, but would such a thing be useful at all?

**Comment by MolarAmbiguity** [comment]
Yes, do you think it should be implemented in a manner similar to axispairs?

**Comment by tesselode** [comment]
Axis pairs are fundamentally different, so no? The reason I ask is because, as far as I can tell, joystick hats are similar to arrow keys, but the LOVE API makes it seem most natural to consider them 8 different buttons. I'm not sure which way makes the most sense to implement them. And if it does make sense to implement joystick hats as 8 different buttons, why not make any set of 4 directions 8 buttons?

Either way, I'm definitely interested in implementing joystick hats, and your implementation seems pretty good, I'm just trying to ask myself thorough design questions.

**Comment by MolarAmbiguity** [comment]
Thorough design questions are great!

My thinking in relating dpads to axis pairs is that where axispairs are a group of two axes, a dpad would be a group of four buttons, most probably dpdown, dpup, dpleft, and dpright.

Does this make sense? I might be overthinking this issue.

**Comment by tesselode** [comment]
yessss??? the current axis pair implementation lets you do the same thing with both axes and buttons.  what are you asking?

**Comment by MolarAmbiguity** [comment]
I was just kinda thinking out loud.

If you're happy with this PR, I say we merge it. If 8 directional dpads become a requested or necessary feature in the future, address it then.

**Comment by tesselode** [comment]
That's fair. I'm still not sure whether joystick hats should be 4 buttons or 8, but since you actually had a use for them and you saw it fit to design them this way, and since this way is what the LOVE API is already doing, I'll just go with this for now. If someone sees a need to change it, they can make another PR or issue.

**Pull request merged**
