### PR TITLE
readme: Put distinguishing features in first sentence

### PR DESCRIPTION
**Pull request by idbrii**
I skipped over baton when first looking for input libraries because nothing seemed unique about it. Had I known it supported multiple players and gamepads, I would have picked it.

### CODE REVIEW

**Comment by tesselode** [comment]
what do you mean by multiple "modes"?

**Comment by idbrii** [comment]
If you made a GTA2-style game, you can baton.new a separate instance for your pause menu (up, down, accept, cancel), your on-foot (move, aim, shoot, punch), and your driving (steer, accelerate, brake). In this case, menu/on-foot/drive would be different modes.

It's something I wished I had when working in Unreal, so I thought it was a stand-out feature of baton! It's also something that other love2d input systems I looked at didn't have (you often define a single table of possible inputs).

**Comment by tesselode** [comment]
i'm not sure having separate control modes is a common use case, but i will add something about having multiple player instances

**Comment by tesselode** [comment]
added a little extra text to the readme in 4d44f220f9bab80453515bc3aa07ba52b024a1b4

**Pull request closed without merging**
